name: Dockerhub
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: huseyinyilmaz/namaste-mysql-adapter
        tag_with_ref: true
